### ISSUE TITLE
Option to hide the current date

### ISSUE THREAD

**Issue by hagst** [CocoCR300/flauncher#10]
I would like the option to hide the current date or the option to use a space as date. 
Currently i use a . as date.
I like that the current time is shown. But perhaps others would like the option to hide the current time.

**Comment by CocoCR300** [comment]
Should be done with 75eb67d. Now there is a “Status bar” section on the settings that let you hide the date and time widgets.

It has some issues, for some reason the widget doesn't update correctly when disabling just the date part, or re-enabling it. But switching to the full screen clock and then back to the apps, or performing a restart of the launcher, fixes it. Shouldn't be an issue after choosing the preferred widgets.

**Comment by hagst** [comment]
Thanks for the options and they are working for me. 
One side note: i can only make my choice by using a mouse. 
My official remote (Shield TV Pro 2019 with Android TV 11) can't change the 2 settings.
