### ISSUE TITLE
Add the same effect to switches when using a remote as when using a mouse

### ISSUE THREAD

**Issue by hagst** [CocoCR300/flauncher#19]
When hovering on one of the four switches ("Date", "Time", "App card Highlight Animation" 
and "Show category titles") with a mouse you see an effect. 
I would like to see the same effect when using a remote.

**Comment by CocoCR300** [comment]
Not sure if it's the same effect, but now, the items containing those switches have the same highlight as the other buttons. It's added with commit [00a0088](https://github.com/CocoCR300/flauncher/commit/00a0088dd83ea10ae5730799175aa4884b561373).

**Comment by hagst** [comment]
Thanks, this solution works for me.
