### ISSUE TITLE
Unable to longpress

### ISSUE THREAD

**Issue by celenityy** [CocoCR300/flauncher#21]
Previously, you were able to longpress apps to organize & sort them. This appears to be broken with the latest release? 

Device: NVIDIA Shield TV Pro 2019

Version: Latest

Please let me know if you need any other details :)

**Comment by CocoCR300** [comment]
Can reproduce. I will try to fix this now. Thanks for the report;

**Comment by CocoCR300** [comment]
The most recent commit [278984f](https://github.com/CocoCR300/flauncher/commit/278984fd62be993dd77d408070aa09843ab9d6e2) includes a fix for this. Should be good now.
And now I realize that, at least, I need build numbers for bug reports.

**Comment by hagst** [comment]
Thanks for fixing this problem.  Longpress is working again.

**Comment by hagst** [comment]
Longpress is broken after 507ca85 when using an official NVIDIA Shield TV Pro 2019 remote.
