### ISSUE TITLE
Feature Request: Hide category names

### ISSUE THREAD

**Issue by ACR-Jeff** [CocoCR300/flauncher#25]
I love your fork btw, It would be nice to have an option to hide categories names on home screen.
Thank you

**Comment by hagst** [comment]
This is already possible. 
"There's a new option in the settings to provide this feature."
source: https://github.com/CocoCR300/flauncher/issues/6#issuecomment-2195664305

**Comment by ACR-Jeff** [comment]
> This is already possible. "There's a new option in the settings to provide this feature." source: [#6 (comment)](https://github.com/CocoCR300/flauncher/issues/6#issuecomment-2195664305)

Thank you for responding, 
I have installed the latest version 0.0.1 me.efesser.flauncher installed it and that option is not visible in the settings menu on nvidia shield 2017 firmware 8.2.3

**Comment by ACR-Jeff** [comment]
Ok noob error here, I found it. It would have been smart of me to scroll down the settings, Now I feel really ignorant LMAO. Thank you
