### ISSUE TITLE
Feature Request: empty category (and use it as a spacer)

### ISSUE THREAD

**Issue by ACR-Jeff** [CocoCR300/flauncher#26]
Ability to create a fully empty category (and use it as a spacer) or any way to add padding 

![LauncherPadding](https://github.com/user-attachments/assets/b68f648e-150b-4097-a39c-11ddc0ed7b0e)

I ran across an FLauncher fork which is older then your fork, aLauncher they call it.
https://github.com/4v3ngR/aLauncher

They have added an option to allow a blank category to use as a spacer. This would be awesome to have implemented, 

Just an example of what I have found, Hope this can be implemented
Thank you

https://github.com/4v3ngR/aLauncher/blob/42d66a55c24762e0f685c4ca3c5725ad7eeb6c6e/lib/widgets/category_row.dart#L83-L120

```
  Widget _emptyState(BuildContext context) => category.name.startsWith("_") ?
      SizedBox(
        height: category.rowHeight.toDouble(),
      ) :
      SizedBox(
        height: 110,
        child: EnsureVisible(
          alignment: 0.1,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 8),
            child: Align(
              alignment: Alignment.centerLeft,
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: Card(
                  clipBehavior: Clip.antiAlias,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  child: InkWell(
                    onTap: () => showDialog(
                      context: context,
                      builder: (_) => SettingsPanel(initialRoute: CategoriesPanelPage.routeName),
                    ),
                    child: Padding(
                      padding: EdgeInsets.all(8),
                      child: Center(
                        child: Text(
                          "This category is empty.",
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
```

**Comment by CocoCR300** [comment]
I just released a new version that includes this feature. I renamed the "Categories" page in the settings to "Sections", from there you can add a spacer almost the same way as a category, just select "Spacer" instead of "Category" in the corresponding page.
