### ISSUE TITLE
reopen issue 21 "Unable to longpress"

### ISSUE THREAD

**Issue by hagst** [CocoCR300/flauncher#27]
Longpress is broken after 507ca85 when using an official NVIDIA Shield TV Pro 2019 remote.

_Originally posted by @hagst in https://github.com/CocoCR300/flauncher/issues/21#issuecomment-2336853884_

**Comment by ACR-Jeff** [comment]
Came here for the same thing, Long press is completely broken, Any presses with a D pad or left mouse button will cause the app to open. No long press to allow for the context menu. Nvidia Shield 2017

**Comment by ACR-Jeff** [comment]
I wish the previous versions weren't overwritten or older actions not removed. I would have went back and installed what I had prior to this, Without the long press you have to have a mouse or keyboard with a track pad in order to move any icons to your desired placement.

**Comment by celenityy** [comment]
> I wish the previous versions weren't overwritten or older actions not removed.

Agreed. The 'continuous' release also makes it harder to install & update this through apps like Obtainium. Would be nice to have some kind of versioning & releases - nothing fancy at all, could even just be based off date.

**Comment by ACR-Jeff** [comment]
> That's the reason i keep the older apk's (currently only the arm64-v8a version) so i can go back to an older version (with a remark in the filename of a problem or solution).
> 
> It would be nice to be able to download older versions. Older versions can be seen at https://github.com/CocoCR300/flauncher/actions but no way to download them.
> 
> The version before the [507ca85](https://github.com/CocoCR300/flauncher/commit/507ca8561e5f711a3851adddf37dc85b9994fe22) update (remove the .txt after downloading) [flauncher-arm64-v8a-release_CocoCR300_2024-07-16_278984f.apk.txt](https://github.com/user-attachments/files/16960814/flauncher-arm64-v8a-release_CocoCR300_2024-07-16_278984f.apk.txt)

Wow thank you, Thank You, It's working great now, I will be sure to do this, I usually do save them as a backup but this time I didn't for some odd reason. I will be for now on though.

**Comment by hagst** [comment]
@CocoCR300 Thank you for:
- reopening https://github.com/CocoCR300/flauncher/issues/21
- update 1c0131d
- closing https://github.com/CocoCR300/flauncher/issues/21 after releasing the update
- adding a version number
- keep the older release
- a fix for https://github.com/CocoCR300/flauncher/issues/21 and keep https://github.com/CocoCR300/flauncher/issues/9 working. 
I will let you known if the are any problems after the 1c0131d update.
