### ISSUE TITLE
BUG：The parameter name for uninstalling the application is incorrect

### ISSUE THREAD

**Issue by SuZhelevel6** [CocoCR300/flauncher#35]
## in lib/providers/apps_service.dart：

you set The package name parameter when deleting the APP is `packageName`
~~~
case "PACKAGE_REMOVED":
await _database.deleteApps([packageName]);
~~~

## But ,in LauncherAppsEventStreamHandler.java

you  set  The package name parameter when deleting the APP is `activityInfo`
~~~
                    "action", "PACKAGE_REMOVED",
                   "activityInfo", packageName));
~~~

## result

This causes the dart layer to be unable to obtain the package name correctly, resulting in errors when deleting the app

Modifying any parameter to synchronize it can solve this problem

**Comment by CocoCR300** [comment]
Nice catch. Thanks for the report. I'm fixing this now.
