### ISSUE TITLE
Allow to change the position of the icons

### ISSUE THREAD

**Issue by bt4ibwem8** [CocoCR300/flauncher#37]
Now the icons are at the top, but I would like to have them at the bottom.

**Comment by CocoCR300** [comment]
With "icons", do you refer to the rectangles that represent each application, or the icons in the status bar?

**Comment by bt4ibwem8** [comment]
rectangles

**Comment by CocoCR300** [comment]
It's not exactly what you want, but the latest release includes "spacers", so you could add a spacer at the top, with enough height to leave the categories at the bottom.

**Comment by bt4ibwem8** [comment]
i tested it today and it looks good, thanks for implementing it
