### ISSUE TITLE
Disable the title of categories

### ISSUE THREAD

**Issue by bt4ibwem8** [CocoCR300/flauncher#6]
It would be more polished if only icons would be visible on the main screen.

**Comment by ptlambert** [comment]
I'm seconding this suggestion to allow empty titles for categories.  If implemented, hopefully include an option to collapse the space where the title would have been?

**Comment by bt4ibwem8** [comment]
@ptlambert 
you can try [alauncher](https://github.com/4v3ngR/alauncher) which has this option in the settings.

**Comment by hagst** [comment]
I would like this option. As already mentioned alauncher has this option, but has other limitations.

**Comment by CocoCR300** [comment]
It's now implemented with 384bdf4. There's a new option in the settings to provide this feature.
