### ISSUE TITLE
allow launching with mouse/touch

### ISSUE THREAD

**Issue by hagst** [CocoCR300/flauncher#9]
I would like to have the option to launch apps with a mouse by 1 click like aLauncher instead of 2 separate clicks. 
Perhaps you could adapt the solution mentioned in https://github.com/4v3ngR/aLauncher/commit/201f10b3df2a4fabd8572f0daf2f1a7bc7a55f5c

**Comment by doug8888** [comment]
Is this why I can launch apps with a cheap bluetooth remote from ebay but when I pair an amazon firestick remote I can only highlight an app but not open it?
Thanks

**Comment by CocoCR300** [comment]
Should be done with 42eeb10. Let me know of any problems you encounter.

**Comment by doug8888** [comment]
Works fine now, thanks.

**Comment by hagst** [comment]
Seems to work just fine. Thank you for making this possible.

**Comment by hagst** [comment]
It looks like this is broken with 278984f.
After uninstall and install the problem stays the same.

**Comment by hagst** [comment]
It looks like this is broken with 278984f.
After uninstall and install the problem stays the same.

**Comment by doug8888** [comment]
Same here, updated to latest version and Firestick remote no longer works.

**Comment by CocoCR300** [comment]
It's fixed with commit [507ca85](https://github.com/CocoCR300/flauncher/commit/507ca8561e5f711a3851adddf37dc85b9994fe22). I had the fix ready for some days, but couldn't test it until now.

**Comment by doug8888** [comment]
Thanks, working now

**Comment by hagst** [comment]
Thanks for the update. Looks good to me.
